<a href="https://colab.research.google.com/github/jleacock2020/CourseraDataAnalystWork/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY

![](numpy1.png)

### Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

#### A numpy array is a grid of values, all of the same type.
#### The number of dimensions is the rank of the array;
#### The shape of an array is a tuple of integers giving the size of the array along each dimension.

![](numpy.png)

In [ ]:
L=[2,3,4,5,6]
L2=[3,4,5,6,7]

# print(L+L2)
# print(L+2)

# L=[5,7,....]

In [ ]:
import numpy as np
arr=np.array([2,3,4,5])
arr2=np.array([2,3,4,5])
print(arr)
print(arr2)
print(arr-arr2)



[2 3 4 5]
[2 3 4 5]
[0 0 0 0]


In [ ]:
import numpy as np

In [ ]:
a = np.array(42) #one element
b = np.array([1, 2, 3, 4, 5]) #one dimensional
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

# print(a)
# print(a.ndim)
#print(b.ndim)
#print(c.ndim)
print(d.ndim)
# print(d)
print(type(a))
# print(c)
print(d.shape)

3
<class 'numpy.ndarray'>
(2, 2, 3)


##### Creating 1D array

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [ ]:
print(a+2)

[3 4 5]


##### Type & Shape

In [ ]:
print(type(a))
print(a.shape)

<class 'numpy.ndarray'>
(3,)


In [ ]:
print(a[0], a[2])

1 3


##### Changing array element

In [ ]:
a[0] = 5
print(a[0])

5


In [ ]:
import numpy as np
arr=np.arange(1,20,4)
arr2=np.array([1,2,3,4,5,6,7])
print(arr)
print(arr2)

[ 1  5  9 13 17]
[1 2 3 4 5 6 7]


##### Creating 2D array

In [ ]:
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])
print(b)

(2, 3)
1 2 4
[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])

sum_result = np.sum(array)
mean_result = np.mean(array)
std_result = np.std(array)

print("Sum:", sum_result)
print("Mean:", mean_result)
print("Standard Deviation:", std_result)

Sum: 15
Mean: 3.0
Standard Deviation: 1.4142135623730951


##### Create an array of all zeros

In [ ]:
a = np.zeros((3,4))
print(a)
print(a.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64


##### Create an array of all ones

In [ ]:
b = np.ones((1,2))
print(b)

[[1. 1.]]


##### Create a constant array

In [ ]:
c = np.full((2,2), 7)
print(c)
print(c.dtype)

[[7 7]
 [7 7]]
int32


##### Create a 2x2 identity matrix

In [ ]:
d = np.eye(4)
print(d)
print(d.dtype)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
float64


##### Create an array filled with random values

In [ ]:
e = np.random.random((2,2))
print(e)

[[0.64033068 0.49774927]
 [0.64720931 0.01970816]]


### Array indexing

#### Numpy offers several ways to index into arrays.

#### Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

##### Create the following rank 2 array with shape (3, 4)

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

In [ ]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
b = a[:2, 1:3]
print(b)


In [ ]:
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
c = a[:2, 1:3]
print(c)
c[0, 0] = 77
print(c[0, 0])

In [ ]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

In [ ]:
# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

In [ ]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

### Datatypes

#### Every numpy array is a grid of elements of the same type.
#### Numpy provides a large set of numeric datatypes that you can use to construct arrays.
#### Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype.

In [ ]:
x = np.array([1, 2.0])
print(x.dtype)

x = np.array([1.0, 2.0])
print(x.dtype)

x = np.array([True, 2.5], dtype=np.int64)
print(x.dtype)
print(x)

### Array math

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
#x = np.array([[1,2],[3,4]])
#y = np.array([[5,6],[7,8]])
# Elementwise sum; both produce the array
#print(x)
print(x + y)

print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [ ]:
# Elementwise difference; both produce the array

print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


![](numpy-matrix-product.png)

In [ ]:
# Elementwise product; both produce the array
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print(x * y)
print(np.multiply(x, y))

#print(np.dot(x,y))
print(np.matmul(x,y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[19. 22.]
 [43. 50.]]


In [ ]:
# Elementwise division; both produce the array

print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
# Elementwise square root; produces the array
x = np.array([[1,2],[3,4]], dtype=np.float64)
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


##### Assigning x,y,v&w

In [ ]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([5,10])
w = np.array([11, 4])

In [ ]:
# Inner product of vectors
print(v.dot(w))
print(np.dot(v, w))

In [ ]:
# Matrix / vector product; both produce the 1D array [29 67]
print(x.dot(v))
print(np.dot(x, v))

In [ ]:
# Matrix / matrix product; both produce the 2D array

print(x.dot(y))
print(np.dot(x, y))

### SUM FUNCTION

In [ ]:
x = np.array([[1,2],[3,4]])
print(x)

print(np.sum(x))  # Compute sum of all elements;
print(np.sum(x, axis=0))  # Compute sum of each column;
print(np.sum(x, axis=1))  # Compute sum of each row;

[[1 2]
 [3 4]]
10
[4 6]
[3 7]


## Arithmetic Operations:

#### Addition: np.add(a,b)
#### Subtraction:np.subtract(a,b)
#### Multiplication: np.multiply(a,b)
#### Division: np.divide(a,b)
#### Exponentiation: np.exp(a)
#### Square Root: np.sqrt(b)


### Comparison
#### Element-wise: a==b
#### Array-wise: np.array_equal(a,b)

### Copying:
#### np.copy(array) – Copies array to new memory array.
#### view(dtype) – Creates view of array elements with typedtype

### Sorting:
#### array.sort() – Sorts array
#### array.sort(axis=0) – Sorts specific axis of array
#### array.reshape(2,3) – Reshapes array to 2 rows, 3 columns without changing data.

In [ ]:
arr=np.arange(5,20)
print(arr.shape)
print(arr.reshape(3,5))

(15,)
[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


### Adding:
#### np.append(array,values) – Appends values to end of array
#### np.insert(array,4,values) – Inserts values into array before index 4

### Removing:
#### np.delete(array,2,axis=0) – Deletes row on index 2 of array
#### np.delete(array,3,axis=1) – Deletes column on index 3 of array

### Combining:
#### np.concatenate((array1,array2),axis=0) – Adds array2 as rows to the end of array1
#### np.concatenate((array1,array2),axis=1) – Adds array2 as columns to end of array1

### Splitting:
#### np.split(array,3) – Splits array into 3sub-arrays

### Indexing:
#### a[0]=5 – Assigns array element on index 0 the value 5
#### a[2,3]=1 – Assigns array element on index [2][3] the value 1

### Subsetting:
#### a[2]: Returns the element of index 2 in array a.
#### a[3,5] – Returns the 2D array element on index [3][5]

### Slicing:
#### a[0:4] – Returns the elements at indices 0,1,2,3
#### a[0:4,3] – Returns the elements on rows 0,1,2,3 at column 3
#### a[:2] – Returns the elements at indices 0,1
#### a[:,1] – Returns the elements at index 1 on all rows

In [ ]:
#https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises_with_solutions.md

In [ ]:
import numpy as np
T=np.linspace(1,2,8)
print(T)

[1.         1.14285714 1.28571429 1.42857143 1.57142857 1.71428571
 1.85714286 2.        ]


**PANDAS LIBRARY**

In [ ]:
import pandas as pd

df=pd.read_csv("Chicago_Public_School.csv")
df.head()


School ID                                     NAME_OF_SCHOOL  \
0     610038                  Abraham Lincoln Elementary School   
1     610281  Adam Clayton Powell Paideia Community Academy ...   
2     610185                Adlai E Stevenson Elementary School   
3     609993                    Agustin Lara Elementary Academy   
4     610513                      Air Force Academy High School   

  Elementary, Middle, or High School          Street Address     City State  \
0                                 ES        615 W Kemper Pl   Chicago    IL   
1                                 ES  7511 S South Shore Dr   Chicago    IL   
2                                 ES     8010 S Kostner Ave   Chicago    IL   
3                                 ES     4619 S Wolcott Ave   Chicago    IL   
4                                 HS        3630 S Wells St   Chicago    IL   

   ZIP Code    Phone Number  \
0     60614  (773) 534-5720   
1     60649  (773) 535-6650   
2     60652  (773) 535-2280   
3     60609  (773) 535-4389   
4     60609  (773) 535-1590   

                                               Link   \
0  http://schoolreports.cps.edu/SchoolProgressRep...   
1  http://schoolreports.cps.edu/SchoolProgressRep...   
2  http://schoolreports.cps.edu/SchoolProgressRep...   
3  http://schoolreports.cps.edu/SchoolProgressRep...   
4  http://schoolreports.cps.edu/SchoolProgressRep...   

                      Network Manager  ... Freshman on Track Rate %  \
0        Fullerton Elementary Network  ...                      NDA   
1           Skyway Elementary Network  ...                      NDA   
2           Midway Elementary Network  ...                      NDA   
3         Pershing Elementary Network  ...                      NDA   
4  Southwest Side High School Network  ...                     91.8   

  X_COORDINATE Y_COORDINATE   Latitude  Longitude COMMUNITY_AREA_NUMBER  \
0  1171699.458  1915829.428  41.924497 -87.644522                     7   
1  1196129.985  1856209.466  41.760324 -87.556736                    43   
2  1148427.165  1851012.215  41.747111 -87.731702                    70   
3  1164504.290  1873959.199  41.809757 -87.672145                    61   
4  1175177.622  1880745.126  41.828146 -87.632794                    34   

  COMMUNITY_AREA_NAME  Ward Police District                     Location  
0        LINCOLN PARK    43              18  (41.92449696, -87.64452163)  
1         SOUTH SHORE     7               4  (41.76032435, -87.55673627)  
2             ASHBURN    13               8  (41.74711093, -87.73170248)  
3            NEW CITY    20               9    (41.8097569, -87.6721446)  
4       ARMOUR SQUARE    11               9  (41.82814609, -87.63279369)  

[5 rows x 78 columns]